### ISSUE TITLE
Activating bp-rewrites breaks page_on_front

### ISSUE THREAD

**Issue by boonebgorges** [buddypress/bp-rewrites#11]
**Describe the bug**
Activating bp-rewrites breaks page_on_front

**To Reproduce**
1. Without bp-rewrites, set a BP directory page (such as Groups or Members) to page_on_front (Dashboard > Settings > Reading)
2. Visit home page. You should see the selected directory.
3. Activate bp-rewrites.
4. Visit home page. You now get the 404 message. Furthermore, when you visit wp-admin/options-reading.php, the directory page is no longer selected in the dropdown.

I haven't debugged this at all - I wanted to report the bug before I forgot :-D

**Comment by imath** [comment]
Thanks @boonebgorges 

The main reason of this issue is due to the fact, unlike BuddyPress, BP Rewrites uses a specific custom post type. I'll look into it to see how we can preserve the feature 👍
