### ISSUE TITLE
Error on plugin activation

### ISSUE THREAD

**Issue by teboy** [buddypress/bp-rewrites#24]
**Describe the bug**
1. I could not activate the bp rewrites plugin I keep getting the error that (the following link has expired)
2.  After trying to activate without any success I also noticed that all my current buddypress pages were totally deleted.

**WP/BP Configuration (please complete the following information):**
 - WordPress: [version 5.9]
 - BuddyPress [version 10.0]

**Comment by imath** [comment]
Hi @teboy 

Thanks for you report and sorry to read you had this issue. I wasn't able to replicate it and I believe it's not related to the BP Rewrites plugin. If you got this error `The link you followed has expired.` after clicking on the link to activate the plugin, this means the security nonce WordPress is adding to the activate link was generated more than 24 hours ago.

Do you have any plugin, custom script overriding the WordPress `check_admin_referer()` or adding an action to the hook `check_admin_referer` ?

Could you try activating any other plugin to see if you get the same error?

**Comment by imath** [comment]
As we haven't heard of this since February 13, I'm considering the issue has vanished 😄 Don't hesitate to reopen the issue if it comes back.
