### ISSUE TITLE
Fatal error when trying to activate/deactivate BP-Rewrites if BuddyPress has been deactivated or doesn't exists

### ISSUE THREAD

**Issue by adiloztaser** [buddypress/bp-rewrites#29]
Should we consider this situations?

Error:
```
Fatal error: Uncaught Error: Call to undefined function BP\Rewrites\bp_core_get_directory_pages()
in /var/www/html/wp-content/plugins/bp-rewrites/inc/update.php on line 22
```

**Comment by imath** [comment]
Yes absolutely !! Thanks for catching it, I’ll try to understand why this is happening. I believe the file where this function is located might not be included yet.

imath
https://imathi.eu
________________________________
De : Adil Öztaşer ***@***.***>
Envoyé : Tuesday, February 15, 2022 10:31:27 PM
À : buddypress/bp-rewrites ***@***.***>
Cc : Subscribed ***@***.***>
Objet : [buddypress/bp-rewrites] Fatal error when trying to activate/deactivate BP-Rewrites if BuddyPress has been deactivated or doesn't exists (Issue #29)


Should we consider this situations?

Error:

Fatal error: Uncaught Error: Call to undefined function BP\Rewrites\bp_core_get_directory_pages()
in /var/www/html/wp-content/plugins/bp-rewrites/inc/update.php on line 22
