### ISSUE TITLE
issues on multisite / BP network activated

### ISSUE THREAD

**Issue by eha1** [buddypress/bp-rewrites#32]
Hi, i just tested Version 1.0.0-beta2 on my wp multisite install with BP network aktivated and it does not work, the plugin seems to expect BP to be activted on the main site instead of network activated, posts error "BP Rewrites requires the [BuddyPress](https://wordpress.org/plugins/buddypress) plugin to be active. Please deactivate BP Rewrites, activate [BuddyPress](https://wordpress.org/plugins/buddypress) and only then, reactivate BP Rewrites."

tested also to have BP network activated and the rewrite plugin activated on the main site, without success.

br, Eric

**Comment by imath** [comment]
Hi @eha1 

Thanks a lot for your feedback, I see what's the problem. I'm going to add a Pull Request to fix it.
