### ISSUE TITLE
 Undefined variable: structs

### ISSUE THREAD

**Issue by shanebp** [buddypress/bp-rewrites#6]
<html>
<body>

On every page:  Notice > Undefined variable: `structs` in 
`wp-content/plugins/bp-rewrites-trunk/src/bp-blogs/classes/class-blogs-component.php:262`

Perhaps this: ` return parent::add_permastructs( $structs );`
Should be `return parent::add_permastructs( $permastructs );`

</body>
</html>

**Comment by imath** [comment]
Hi @shanebp 

Thanks a lot for your report. You're completely right.

line 262 of the file should be:
```php
return parent::add_permastructs( $permastructs );
```

I'll fix this asap, unless someone suggests a PR about it 😉

**Comment by shanebp** [comment]
PR sent.  Somehow made 3 commits to the PR, instead of one, sorry.

**Comment by imath** [comment]
Thanks a lot for your PR, it's fixed 💪
