### ISSUE TITLE
Group Extension > group id in construct

### ISSUE THREAD

**Issue by shanebp** [buddypress/bp-rewrites#9]
Using a custom BP component... 
Using a BP_Group_Extension, in `__construct()` I need to get the group id so I can retrieve a groupmeta value and determine if a tab should be added.  
This works when the Rewrites plugin is not active: 
```
class Group_Events extends BP_Group_Extension {
    function __construct() {

	$setting = groups_get_groupmeta( $this->get_group_id(), 'events-assignable'  );

	if ( $setting == '1' ) {
		$show_tab = 'anyone';
	} else {
		$show_tab = 'noone';
	}  // etc 
```
With the Rewrites plugin active, `$this->get_group_id()`  is always zero and so the tab is never added. 
Also tried using `bp_get_group_id()`  and `$this->group_id`

**Comment by imath** [comment]
Hi @shanebp 

Thanks a lot for your report. To be honest, I haven't checked the Group Extension use yet. I was suspecting issues in this area. We need to fix them for sure. I'll have a look at it asap to figure out the adaptations needed to make BP Group Extension behave the way it should.

**Comment by boonebgorges** [comment]
It's likely that this is the same issue as #7, because the `__construct()` methods run earlier than `bp_parse_query`.

**Comment by imath** [comment]
As @boonebgorges was thinking now #7 has been fixed, you should be able to get the group ID into your `__construct()` @shanebp. But if you have `WP_DEBUG` set to true, you'll also get a `_doing_it_wrong()` output.

I'll see how I can avoid this by delaying Group Extensions registrations to the `bp_parse_query`  hook.

**Comment by imath** [comment]
I need to edit BuddyPress Core to progress here. FYI, here's the [ticket](https://buddypress.trac.wordpress.org/ticket/8558) I just opened on BP Trac.
